# Generated by Django 3.2.7 on 2021-09-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210916_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryManager',
        ),
    ]
