# Generated by Django 3.2.7 on 2021-09-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210918_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название детали')),
                ('code', models.CharField(max_length=150, verbose_name='Код детали')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.manufacturer', verbose_name='Производитель')),
            ],
        ),
        migrations.RemoveField(
            model_name='exhaustsystem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exhaustsystem',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='category',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='fuelsystem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fuelsystem',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='ignition',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ignition',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='suspension',
            name='category',
        ),
        migrations.RemoveField(
            model_name='suspension',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='object_id',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Карзина'),
        ),
        migrations.DeleteModel(
            name='Breaks',
        ),
        migrations.DeleteModel(
            name='ExhaustSystem',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.DeleteModel(
            name='FuelSystem',
        ),
        migrations.DeleteModel(
            name='Ignition',
        ),
        migrations.DeleteModel(
            name='Suspension',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='carpart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.carpart', verbose_name='Деталь'),
            preserve_default=False,
        ),
    ]
